## refs: https://github.com/project-openwrt/build-openwrt/blob/master/.github/workflows/main.yml

name: lede

on:
  push:
    branches:
      - master

env:
  OPENWRT_SOURCE_DIR: /home/runner/work/BuildOpenWRT/BuildOpenWRT/lede

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Checkout Submodule
        run: |
          git submodule update --init --recursive
      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update -y
          #sudo -E apt-get full-upgrade -y
          sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler
          sudo -E ln -sf /usr/bin/gcc-8 /usr/bin/gcc
          sudo -E ln -sf /usr/bin/g++-8 /usr/bin/g++
          sudo -E apt-get autoremove -y --purge
          sudo -E apt-get clean -y
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php
      - name: Configurate
        run: |
          ./build_lede.sh --feeds
      - name: Download
        run: |
          cd $OPENWRT_SOURCE_DIR
          make download -j8 || true
          make download -j8 || true
          make download -j8 || true
          make download -j8 || true
      - name: Make
        run: |
          cd $OPENWRT_SOURCE_DIR
          let make_process=$(nproc)+1
          make -j${make_process} || make -j1 || make -j1 V=s
      - name: Upload Packages
        uses: actions/upload-artifact@master
        with:
          name: Packages
          path: lede/bin/packages/
      - name: Upload Config
        uses: actions/upload-artifact@master
        with:
          name: config.seed
          path: lede/bin/packages/x86/64/config.seed
      - name: Upload ext4 img
        uses: actions/upload-artifact@master
        with:
          name: config.seed
          path: lede/bin/packages/x86/64/openwrt-x86-64-combined-ext4.img.gz
      - name: Upload ext4 vmdk
        uses: actions/upload-artifact@master
        with:
          name: config.seed
          path: lede/bin/packages/x86/64/openwrt-x86-64-combined-ext4.vmdk
      - name: Upload squashfs img
        uses: actions/upload-artifact@master
        with:
          name: config.seed
          path: lede/bin/packages/x86/64/openwrt-x86-64-combined-squashfs.img.gz
      - name: Upload squashfs vmdk
        uses: actions/upload-artifact@master
        with:
          name: config.seed
          path: lede/bin/packages/x86/64/openwrt-x86-64-combined-squashfs.vmdk
      - name: sha256sums
        uses: actions/upload-artifact@master
        with:
          name: config.seed
          path: lede/bin/targets/x86/64/sha256sums


